### ISSUE TITLE
Podfile issue

### ISSUE THREAD

**Issue by ManuConstantin** [bhoominn/nb_utils#1]
There is an error when trying to install nb_utils because the string in s.summary contains an 
apostrophe without escaping.

Pod::Spec.new do |s|
  s.name             = 'nb_utils'
  s.version          = '0.0.1'
  s.summary          = 'This package helps you daily usable function with ease. Just add nb_utils with its latest version and that's it you are ready to use.'
  s.description      = <<-DESC

**Comment by bhoominn** [comment]
Got it. Will fix it very soon.
Thanks
