### ISSUE TITLE
Shared preferences

### ISSUE THREAD

**Issue by jacky501** [bhoominn/nb_utils#10]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: LateInitializationError: Field 'sharedPreferences' has not been initialized.
E/flutter ( 7771): #0      sharedPreferences (package:nb_utils/nb_utils.dart)
E/flutter ( 7771): #1      getStringAsync (package:nb_utils/src/utils/shared_pref.dart:68:10)

**Comment by bhoominn** [comment]
It looks like you forget to initialize nb_utils library. See below.

`
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  **await initialize();**

  runApp(MyApp());
}
`

**Comment by jacky501** [comment]
Thank you. (Solved)
