### ISSUE TITLE
nested showConfirmDialogCustom

### ISSUE THREAD

**Issue by NOaMTL** [bhoominn/nb_utils#13]
Hello,

how can I add showConfirmDialogCustom (or other Dialog) inside onAccept function of another showConfirmDialogCustom ?

Thank you

**Comment by bhoominn** [comment]
Try to set cancelable: false in parameter.

**Comment by bhoominn** [comment]
is your issue resolved?

**Comment by bhoominn** [comment]
Hi, I am closing this issue as of now as I haven't received any reply.

Thanks
