### ISSUE TITLE
Can you a screenshot of your code?

### ISSUE THREAD

**Issue by pagolina** [bhoominn/nb_utils#15]
Can you a screenshot of your code?

_Originally posted by @bhoominn in https://github.com/bhoominn/nb_utils/issues/14#issuecomment-1047847453_

**Comment by bhoominn** [comment]
Use log instead of print.

**Comment by pagolina** [comment]
print was inserted when the error occure, so even without the print the error persist

**Comment by bhoominn** [comment]
Can you share full dart file so that i can debug on my PC?

**Comment by pagolina** [comment]
> Can you share full dart file so that i can debug on my PC?

I have resolve the issue, by removing context in onAccept constructor, Thank you i appreciate

**Comment by bhoominn** [comment]
okay, thanks.
