### ISSUE TITLE
In AppButton on set enable: false, child is not rendered because onPressed is forced null

### ISSUE THREAD

**Issue by najeebimrankhan** [bhoominn/nb_utils#18]

**Comment by bhoominn** [comment]
Yes, @najeebimrankhan, I got this issue today, will be working tonight on this bug.

Thanks

**Comment by bhoominn** [comment]
Even you can fix this bug by forking this repo and creating a pull request, I will merge then.

**Comment by bhoominn** [comment]
Actually, the child is being rendered. please share your AppButton code here.

**Comment by najeebimrankhan** [comment]
`Widget myButton(
    {String? text, IconData? iconData, Function? onTap, bool isBusy = false}) {
  
  return AppButton(
    shapeBorder: iconData != null ? const CircleBorder() : null,
    enabled: !isBusy,
    text: text,
    child: (iconData != null
            ? Icon(
                iconData,
                color: white,
                size: Dimens.iconSize,
              )
            : null),
    textColor: white,
    color: clPrimary,
    onTap: onTap,
  );
}`

**Comment by bhoominn** [comment]
I think your text color is also white, and your scaffold color must be white, that's why the child is not visible. otherwise, the child is rendering.

**Comment by najeebimrankhan** [comment]
The primary color (Button Color) is blue. However, @bhoominn let me check the code better after I reach office on Monday.

**Comment by bhoominn** [comment]
Hi, did you checked?

**Comment by bhoominn** [comment]
Can i close this issue? @najeebimrankhan

**Comment by bhoominn** [comment]
Hi, I am closing this issue as of now as I haven't received any reply. 

Thanks.
