### ISSUE TITLE
isYesterday is wrong

### ISSUE THREAD

**Issue by altayevrim** [bhoominn/nb_utils#20]
Hello, 
First of all; great package. It's very useful!

I noticed a mistake.
```
/// Returns true if given date is yesterday
  bool get isYesterday {
    final now = DateTime.now();
    final yesterday = DateTime(now.year, now.month, now.day - 1);

    return DateTime(now.year, now.month, now.day - 1) == yesterday;
  }
```

I think it should be something like this.
```
/// Returns true if given date is yesterday
  bool get isYesterday {
    final now = DateTime.now();
    final yesterday = DateTime(now.year, now.month, now.day - 1);

    return DateTime(this.year, this.month, this.day) == yesterday;
  }
```

Thanks!

**Comment by bhoominn** [comment]
Yes, thanks. I will solve this.

**Comment by altayevrim** [comment]
You're very welcome :)

**Comment by bhoominn** [comment]
this issue has been resolved. please verify in the latest version.

**Comment by altayevrim** [comment]
Hi, I recently saw that there might be problem with isTomorrow as well. Can you check it that too? I don't use that but someone might use it in the future :)

**Comment by bhoominn** [comment]
Yes, I have corrected isTomorrow also.
Thanks.

**Comment by altayevrim** [comment]
You're welcome, I just saw the second commit. Sorry about that. Btw are you sure it is the correct logic?
I fixed it with this;
```
/// Returns true if given date is tomorrow
  bool get isTomorrow {
    final now = DateTime.now();
    final tomorrow = DateTime(now.year, now.month, now.day + 1);

    return DateTime(this.year, this.month, this.day) == tomorrow;
  }
```

**Comment by altayevrim** [comment]
Let's say we are checking the 10th April 2022 is Tomorrow,
you are creating a date instance 2022,04,11 (10 + 1) and you are comparing it with instance of 2022,04,08 (now - 1)
which will be incorrect and return false.

**Comment by bhoominn** [comment]
fixed.

**Comment by bhoominn** [comment]
You can close the issue if both function is working.

**Comment by altayevrim** [comment]
Haven't tested but closing anyway.
