### ISSUE TITLE
Error: No named parameter with the name 'useMaterial3'

### ISSUE THREAD

**Issue by AlaaMarawi** [bhoominn/nb_utils#24]
Hi, thank you for your efforts..
I am depending on v 4.5.2 because of this [issue](https://github.com/bhoominn/nb_utils/issues/21)
Flutter 2.8.1

I am facing an error on app run : 
```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/nb_utils-4.5.2/lib/src/utils/system_utils.dart:156:5: Error: No named parameter with the name 'useMaterial3'.
    useMaterial3: true,
    ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/theme_data.dart:222:11: Context: Found this candidate, but the arguments don't match.
  factory ThemeData({
          ^
```
and build is failed. 
This is showing with the last version as well.

**Comment by bhoominn** [comment]
Please upgrade your Flutter SDK to latest.

**Comment by bhoominn** [comment]
Is your issue solved?

**Comment by AlaaMarawi** [comment]
yes, I upgraded to flutter 3.0.5 and useMaterial3 is not causing an error anymore. (on both v 4.5.2 and latest: 4.6.16)
