### ISSUE TITLE
IOS duration issue

### ISSUE THREAD

**Issue by SHELA** [bhoominn/nb_utils#26]
Error when trying to run flutter on iOS.
`../flutter/.pub-cache/hosted/pub.dartlang.org/nb_utils-4.6.21/lib/src/utils/common.dart:67:20: Error: The argument type 'Duration?' can't be assigned to the parameter type 'Duration' because 'Duration?' is nullable and 'Duration' isn't. - 'Duration' is from 'dart:core'. toastDuration: duration,`

**Comment by saropa** [comment]
Same issue here.

**Comment by bhoominn** [comment]
Hello @SHELA @saropa , this issue has been fixed in the latest version. Please upgrade your library version.

**Comment by bhoominn** [comment]
Can i close this issue now?
