### ISSUE TITLE
Type 'Color' not found: version 4.6.22

### ISSUE THREAD

**Issue by nblauren** [bhoominn/nb_utils#27]
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/nb_utils-4.6.22/lib/src/extensions/string_extensions.dart:112:3: Error: Type 'Color' not found.
  Color toColor({Color? defaultColor}) {
  ^^^^^
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/nb_utils-4.6.22/lib/src/extensions/string_extensions.dart:112:18: Error: Type 'Color' not found.
  Color toColor({Color? defaultColor}) {
                 ^^^^^
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/nb_utils-4.6.22/lib/src/extensions/string_extensions.dart:112:18: Error: 'Color' isn't a type.
  Color toColor({Color? defaultColor}) {
                 ^^^^^

**Comment by dineshkumar02** [comment]
I am also facing the same problem :(

**Comment by irfan512** [comment]
I am also facing same issue

**Comment by irfan512** [comment]
any solution for that?

**Comment by bhoominn** [comment]
Try upgrading Flutter SDK.

**Comment by dineshkumar02** [comment]
This pull request solves the issue.

It is fairly simple change 

https://github.com/bhoominn/nb_utils/pull/28

**Comment by bhoominn** [comment]
The issues has been fixed in the latest version.
