### ISSUE TITLE
ScrollController Extensions scroll to item

### ISSUE THREAD

**Issue by RoyalCoder88** [bhoominn/nb_utils#31]
Hi friends, thanks for your great package, I'm using `AnimatedListView` and I want to scrollTo specific item in list, how can I get the specific item position in list, I tried a lot of things nothing seems to work :( if I'm using jumpTo how I can get the "item pos" when my items in list have different heights? Thanks in advanced!

**Comment by bhoominn** [comment]
Hi,

You can use the scroll controller to achieve that and pass the scroll controller variable in AnimatedListView widget.
