### ISSUE TITLE
: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.

### ISSUE THREAD

**Issue by Shahidbangash** [bhoominn/nb_utils#34]
Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
../…/widgets/overlay_custom_widget.dart:99
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/overlay.dart').
package:flutter/…/widgets/overlay.dart:1
Try calling using ?. instead.
    Overlay.of(context).insert(entry);
                        ^^^^^^
: Error: Type 'EditableTextContextMenuBuilder' not found.
../…/widgets/app_text_field.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: 'EditableTextContextMenuBuilder' isn't a type.
../…/widgets/app_text_field.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: No named parameter with the name 'contextMenuBuilder'.
../…/widgets/app_text_field.dart:353
      contextMenuBuilder: widget.contextMenuBuilder,
      ^^^^^^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
../…/material/text_form_field.dart:97
  TextFormField({
  ^^^^^^^^^^^^^
3

FAILURE: Build completed with 2 failures.

Here is the flutter doctor Summary

[✓] Flutter (Channel stable, 3.3.7, on macOS 13.1 22C5033e darwin-arm, locale en-PK)
    • Flutter version 3.3.7 on channel stable at /Users/admin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (3 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.1 22C5033e darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by bhoominn** [comment]
You have to upgrade your Flutter SDK to 3.7.0 to if you want to use nb_utils version 5.0.0 or above.

Or else please use 4.6.25 version to run the app.

**Comment by Shahidbangash** [comment]
I upgraded my Flutter Sdk to 3.7.0. Now i get another error.

nb_utils : 5.0.4
Flutter Sdk 3.7.0



Error: Type 'EditableTextContextMenuBuilder' not found.
../…/widgets/app_text_field.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



: Error: 'EditableTextContextMenuBuilder' isn't a type.
../…/widgets/app_text_field.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: No named parameter with the name 'contextMenuBuilder'.
../…/widgets/app_text_field.dart:353
      contextMenuBuilder: widget.contextMenuBuilder,

      ^^^^^^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.

**Comment by Shahidbangash** [comment]
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C5033e darwin-arm64, locale en-PK)
    • Flutter version 3.7.0 on channel stable at /Users/admin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (7 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

**Comment by bhoominn** [comment]
This should be fixed in latest Flutter version.

Try to clean flutter and pub get and let me know.

**Comment by Shahidbangash** [comment]
> This should be fixed in latest Flutter version.
> 
> Try to clean flutter and pub get and let me know.

it worked, Closing this issue
