### ISSUE TITLE
error after updating to 5.0.5

### ISSUE THREAD

**Issue by fabton1963** [bhoominn/nb_utils#36]
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/nb_utils-5.0.5/lib/src/widgets/app_text_field.dart:65:9: Error: Type 'EditableTextContextMenuBuilder' not found.
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/nb_utils-5.0.5/lib/src/widgets/app_text_field.dart:65:9: Error: 'EditableTextContextMenuBuilder' isn't a type.
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/nb_utils-5.0.5/lib/src/widgets/app_text_field.dart:353:7: Error: No named parameter with the name 'contextMenuBuilder'.
      contextMenuBuilder: widget.contextMenuBuilder,
      ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/text_form_field.dart:97:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/nb_utils-5.0.5/lib/src/widgets/overlay_custom_widget.dart:99:25: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
    Overlay.of(context).insert(entry);
                        ^^^^^^

**Comment by bhoominn** [comment]
Please upgrade your Flutter SDK to latest version.

**Comment by fabton1963** [comment]
OK, fixed upgrading SDK.
