### ISSUE TITLE
How to remove Shared Preferences value

### ISSUE THREAD

**Issue by arupnaskarbkp** [bhoominn/nb_utils#4]
Please Explain How to remove Shared Preferences value

**Comment by bhoominn** [comment]
You can use removeKey method to remove shared preference value.

``` dart
await removeKey('key);
```

**Comment by arupnaskarbkp** [comment]
> You can use removeKey method to remove shared preference value.
> 
> ```dart
> await removeKey('key');
> ```

Thanks Sir
