### ISSUE TITLE
Build exception: Flutter app not building due to some error messages from nb_utils

### ISSUE THREAD

**Issue by t-bolt** [bhoominn/nb_utils#40]
This error shows up even when i don't specify a version for nb_utils

![Screenshot from 2023-03-14 19-00-12](https://user-images.githubusercontent.com/45358715/225098123-75566b2d-fd1b-410e-8ae5-b0c5f9d7fcd1.png)
![Screenshot from 2023-03-14 19-02-55](https://user-images.githubusercontent.com/45358715/225098160-431ca730-4a12-4848-a989-5d3487aea88e.png)

**Comment by bhoominn** [comment]
As i can see in the screenshot, you are using very old version of nb_utils.

Please use the latest version and let me know if it solved.

**Comment by t-bolt** [comment]
> As i can see in the screenshot, you are using very old version of nb_utils.
> 
> Please use the latest version and let me know if it solved.

**Comment by bhoominn** [comment]
You can remove connectivity plus package from your pubspec.yaml file and because nb_utils already has it.

You can check await isNetworkAvailable() method to check internet connectivity.

**Comment by bhoominn** [comment]
If you don't added in your pubspec.yaml, please upgrade your Flutter SDK.

**Comment by bhoominn** [comment]
Also use the latest version of nb_utils.

**Comment by t-bolt** [comment]
I  don't have connectivity_plus in my pubspec.yaml.
I have removed the package for now.
I'll have to upgrade my sdk version before i am able to use it.

Btw, can removing the version number of connectivity_plus in nb_utils solve this?
Say:
<pre>connectivity_plus:</pre>

**Comment by bhoominn** [comment]
If i remove the version from the nb_utils, it will detect the latest version by default.

**Comment by t-bolt** [comment]
Oh okay.
I'll go ahead and close the issue now since the only solution I know of is to upd
