### ISSUE TITLE
Upgrading Flutter to 3.10.0

### ISSUE THREAD

**Issue by BenCherif** [bhoominn/nb_utils#43]
Hi,
can you upgrade the flutter version because some dependencies on this library is not updated to be compatible with the new Flutter version  .
Kind regards

**Comment by bhoominn** [comment]
Okay, i am updating today.

**Comment by bhoominn** [comment]
Hi, I have released pre release version of nb_utils.
Please try updating to version 5.0.8-dart3-beta-1 and check again.
