### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by naiemmlbd** [bhoominn/nb_utils#62]
Execution failed for task ':nb_utils:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.

**Comment by Rissmon** [comment]
@naiemmlbd Can you try this https://github.com/bhoominn/nb_utils/issues/55#issuecomment-2314376423.

**Comment by bhoominn** [comment]
Kindly upgrade to nb_utils: ^7.0.5 version.

**Comment by naiemmlbd** [comment]
Thanks.
