### ISSUE TITLE
log('Your string'); Not print full data android studio console

### ISSUE THREAD

**Issue by arupnaskarbkp** [bhoominn/nb_utils#8]
log('Your string');  //Big Data Full print problem

import  nb_utils package any page .. than not add import 'dart:developer'; 

example ---

import 'package:nb_utils/nb_utils.dart';
import 'dart:developer'; // import problem
log('data: $data');

**Comment by bhoominn** [comment]
Do not use import 'dart:developer';

**Comment by arupnaskarbkp** [comment]
but not print api response big data nb utils package log(e)

**Comment by bhoominn** [comment]
Log method uses the default print method of dart. The difference is only that log method will not be called when the app is in release mode.

- Print method can print specific characters in console.
